arch = [
    "base",
    "base-devel",
    "bat",
    "brightnessctl",
    "chafa",
    "docker",
    "docker-compose",
    "efibootmgr",
    "firefox",
    "fnm",
    "fzf",
    "gammastep",
    "git",
    "git-delta",
    "gitoxide",
    "go",
    "golangci-lint",
    "grub",
    "inotify-tools",
    "intel-ucode",
    "jq",
    "kitty",
    "linux",
    "linux-firmware",
    "linux-headers",
    "luarocks",
    "man-db",
    "man-pages",
    "metapac",
    "neovim",
    "networkmanager",
    "noto-fonts-cjk",
    "ntp",
    "okular",
    "openssh",
    "os-prober",
    "paru",
    "pavucontrol",
    "pipewire-audio",
    "pipewire-pulse",
    "python",
    "qt5-wayland",
    "ripgrep",
    "rtkit",
    "rustup",
    "sbctl",
    "sddm",
    "starship",
    "stow",
    "sudo",
    "swaybg",
    "swayfx",
    "swayidle",
    "swaylock",
    "texinfo",
    "texlive-basic",
    "texlive-fontsrecommended",
    "texlive-latex",
    "texlive-latexrecommended",
    "texlive-mathscience",
    "texlive-pictures",
    "thunar",
    "tmux",
    "tree-sitter-cli",
    "ttf-joypixels",
    "vim",
    "waybar",
    "wmenu",
    "xdg-desktop-portal",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-wlr",
    "zig",
    "zsh", "gnupg", "pinentry",
]

