arch = [
  "base",
  "base-devel",
  "bat",
  "btop",
  "brightnessctl",
  "chafa",
  { package = "docker", hooks = { after_sync = [
    "sudo",
    "systemctl",
    "enable",
    "--now",
    "docker.socket",
  ] } },
  "docker-compose",
  "efibootmgr",
  "fastfetch",
  "firefox",
  "fnm",
  "fzf",
  "gammastep",
  "git",
  "git-delta",
  "gitoxide",
  "go",
  "golangci-lint",
  "grub",
  "inotify-tools",
  "intel-ucode",
  { package = "interception-caps2esc", hooks = { after_install = [
    "sudo",
    "cp",
    "~/.dotfiles/udevmon/udevmon.yaml",
    "/etc/interception/udevmon.yaml",
  ], after_sync = [
    "sudo",
    "systemctl",
    "enable",
    "--now",
    "udevmon",
  ] } },
  "jq",
  "kitty",
  "linux",
  "linux-firmware",
  "linux-headers",
  "luarocks",
  "man-db",
  "man-pages",
  "metapac",
  "neovim",
  { package = "networkmanager", hooks = { after_sync = [
    "sudo",
    "systemctl",
    "enable",
    "--now",
    "NetworkManager",
  ] } },
  "noto-fonts-cjk",
  "ntp",
  "okular",
  { package = "openssh", hooks = { after_sync = [
    "sudo",
    "systemctl",
    "enable",
    "--now",
    "sshd",
  ] } },
  "os-prober",
  "paru",
  "pavucontrol",
  "pipewire-audio",
  "pipewire-pulse",
  "python",
  "qt5-wayland",
  "ripgrep",
  "rtkit",
  "rustup",
  "sbctl",
  "gtk-engine-murrine",
  "gtk-engines",
  "nwg-look",
  "obsidian",
  "sassc",
  "ttf-overpass",
  { package = "sddm", hooks = { after_sync = [
    "sudo",
    "systemctl",
    "enable",
    "--now",
    "sddm",
  ] } },
  "starship",
  "stow",
  "sudo",
  "swaybg",
  "swayfx",
  "swayidle",
  "swaylock",
  "texinfo",
  "texlive-basic",
  "texlive-fontsrecommended",
  "texlive-latex",
  "texlive-latexrecommended",
  "texlive-mathscience",
  "texlive-pictures",
  "ttf-joypixels",
  "ttf-overpass",
  "thunar",
  "tmux",
  "tree-sitter-cli",
  "ttf-joypixels",
  "vim",
  "waybar",
  "wmenu",
  "xdg-desktop-portal",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-wlr",
  "zig",
  "zsh",
]
