arch = { packages = [
  "base",
  "base-devel",
  "bat",
  "brightnessctl",
  "btop",
  "chafa",
  "docker",
  "docker-compose",
  "efibootmgr",
  "fastfetch",
  "firefox",
  "fnm",
  "fzf",
  "gammastep",
  "git",
  "git-delta",
  "gitoxide",
  "go",
  "golangci-lint",
  "grub",
  "gtk-engine-murrine",
  "gtk-engines",
  "inotify-tools",
  "intel-ucode",
  "interception-caps2esc",
  "jq",
  "kitty",
  "linux",
  "linux-firmware",
  "linux-headers",
  "luarocks",
  "man-db",
  "man-pages",
  "metapac",
  "neovim",
  "networkmanager",
  "noto-fonts-cjk",
  "ntp",
  "nwg-look",
  "obsidian",
  "okular",
  "openssh",
  "os-prober",
  "paru",
  "paru-debug",
  "pavucontrol",
  "pipewire-audio",
  "pipewire-pulse",
  "python",
  "qt5-wayland",
  "ripgrep",
  "rtkit",
  "rustup",
  "sassc",
  "sbctl",
  "sddm",
  "starship",
  "stow",
  "sudo",
  "swaybg",
  "swayfx",
  "swayidle",
  "swaylock",
  "texinfo",
  "texlive-basic",
  "texlive-fontsrecommended",
  "texlive-latex",
  "texlive-latexrecommended",
  "texlive-mathscience",
  "texlive-pictures",
  "thunar",
  "tmux",
  "tree-sitter-cli",
  "ttf-joypixels",
  "ttf-overpass",
  "vim",
  "waybar",
  "wmenu",
  "xdg-desktop-portal",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-wlr",
  "yamllint",
  "zig",
  "zotero",
  "zsh",
] }
